<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Performance benchmarks for HostLoom.</Description>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <ProjectReference Include="../../src/HostLoom.AspNetCore.WebSockets/HostLoom.AspNetCore.WebSockets.csproj" />
  </ItemGroup>
</Project>
