<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Performance benchmarks for HostLoom.</Description>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="ZiggyCreatures.FusionCache" />
    <ProjectReference Include="../../src/HostLoom.AspNetCore.WebSockets/HostLoom.AspNetCore.WebSockets.csproj" />
    <ProjectReference Include="../../src/HostLoom.Caching/HostLoom.Caching.csproj" />
    <ProjectReference Include="../../src/HostLoom.Locking/HostLoom.Locking.csproj" />
    <ProjectReference Include="../../src/HostLoom.Logging/HostLoom.Logging.csproj" />
    <ProjectReference Include="../../src/HostLoom.Mapping.DependencyInjection/HostLoom.Mapping.DependencyInjection.csproj" />
  </ItemGroup>
</Project>
