using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HostLoom.Composition.Generators;

internal sealed partial class DeclarationCompiler
{
    private GeneratedFile Emit(IMethodSymbol factory)
    {
        string identity =
            _model.Compilation.AssemblyName
            + "."
            + _method.ContainingType.ToDisplayString()
            + "."
            + factory.Name;
        var text = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        INamespaceSymbol space = _method.ContainingNamespace;
        if (!space.IsGlobalNamespace)
            text.Append("namespace ").Append(space.ToDisplayString()).Append("\n{\n");
        var containers = new Stack<INamedTypeSymbol>();
        for (
            INamedTypeSymbol? type = _method.ContainingType;
            type is not null;
            type = type.ContainingType
        )
            containers.Push(type);
        foreach (INamedTypeSymbol type in containers)
            text.Append(Access(type.DeclaredAccessibility))
                .Append(type.IsStatic ? " static" : "")
                .Append(" partial class @")
                .Append(type.Name)
                .Append("\n{\n");
        text.Append("    ")
            .Append(Access(factory.DeclaredAccessibility))
            .Append(" static partial global::HostLoom.Composition.CompositionPlan @")
            .Append(factory.Name)
            .Append("()\n    {\n        return new global::HostLoom.Composition.CompositionPlan(")
            .Append(Literal(identity))
            .Append(", new global::HostLoom.Composition.CompositionRegistration[]\n        {\n");
        foreach (Registration registration in _registrations)
        {
            Rule rule = registration.Rule;
            FileLinePositionSpan position = rule.Syntax.GetLocation().GetLineSpan();
            string path = position.Path.Replace('\\', '/');
            // The development project-reference path supplies no package build props yet.
            // Preserve relative syntax paths, and strip absolute checkout roots from provenance.
            if (
                path.StartsWith("/", StringComparison.Ordinal)
                || (path.Length > 1 && path[1] == ':')
            )
                path = path.Substring(path.LastIndexOf('/') + 1);
            text.Append(
                    "            new global::HostLoom.Composition.CompositionRegistration(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof("
                )
                .Append(TypeName(registration.Service))
                .Append("), typeof(")
                .Append(TypeName(registration.Implementation))
                .Append("), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.")
                .Append(rule.Lifetime)
                .Append("), global::HostLoom.Composition.CompositionCardinality.")
                .Append(rule.Cardinality)
                .Append(", new global::HostLoom.Composition.CompositionOrigin(")
                .Append(
                    Literal(
                        _method.ContainingType.ToDisplayString()
                            + "."
                            + _method.Name
                            + "/rule"
                            + rule.Number.ToString(CultureInfo.InvariantCulture)
                    )
                )
                .Append(", ")
                .Append(rule.Group is null ? "null" : Literal(rule.Group))
                .Append(", ")
                .Append(Literal(path))
                .Append(", ")
                .Append(
                    (position.StartLinePosition.Line + 1).ToString(CultureInfo.InvariantCulture)
                )
                .Append(")),\n");
        }
        text.Append("        });\n    }\n");
        foreach (INamedTypeSymbol _ in containers)
            text.Append("}\n");
        if (!space.IsGlobalNamespace)
            text.Append("}\n");
        string hint =
            "Composition."
            + string.Concat(
                Encoding
                    .UTF8.GetBytes(identity)
                    .Select(static value => value.ToString("x2", CultureInfo.InvariantCulture))
            )
            + ".g.cs";
        return new GeneratedFile(hint, text.ToString());
    }

    private static string Access(Accessibility accessibility) =>
        accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal",
        };

    private static string Literal(string value) =>
        Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    private static string TypeName(INamedTypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string MetadataName(INamedTypeSymbol type) =>
        type.ContainingType is null
            ? type.MetadataName
            : MetadataName(type.ContainingType) + "+" + type.MetadataName;
}
