using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace HostLoom.AspNetCore.WebSockets;

/// <summary>Tracing and metric names and tags emitted by the HostLoom WebSocket gateway.</summary>
public static class WebSocketDiagnostics
{
    /// <summary>Activity source name to enable when configuring OpenTelemetry tracing.</summary>
    public const string ActivitySourceName = "HostLoom.AspNetCore.WebSockets";

    /// <summary>Meter name to enable when configuring OpenTelemetry metrics.</summary>
    public const string MeterName = "HostLoom.AspNetCore.WebSockets";

    /// <summary>Activity name used for a registered WebSocket request operation.</summary>
    public const string RequestActivityName = "hostloom.websocket.request";

    /// <summary>Tag carrying the registered public request operation name.</summary>
    public const string OperationTag = "hostloom.websocket.operation";

    /// <summary>Tag carrying a bounded request outcome.</summary>
    public const string OutcomeTag = "hostloom.websocket.outcome";

    /// <summary>Tag carrying the negotiated WebSocket subprotocol.</summary>
    public const string ProtocolTag = "hostloom.websocket.protocol";

    /// <summary>Tag carrying the registered public topic name.</summary>
    public const string TopicTag = "hostloom.websocket.topic";

    /// <summary>Tag carrying a bounded drop or handshake-rejection reason.</summary>
    public const string ReasonTag = "hostloom.websocket.reason";

    /// <summary>Tag carrying a normalized session close reason.</summary>
    public const string CloseReasonTag = "hostloom.websocket.close_reason";

    /// <summary>Tag carrying a public <see cref="HubFaultCodes"/> value.</summary>
    public const string FaultCodeTag = "hostloom.websocket.fault.code";

    private static readonly ActivitySource Activities = new(ActivitySourceName);
    private static readonly Meter Meter = new(MeterName);

    private static readonly UpDownCounter<long> Sessions = Meter.CreateUpDownCounter<long>(
        "hostloom.websocket.sessions",
        "{session}",
        "Active gateway sessions, tagged by negotiated protocol."
    );

    private static readonly UpDownCounter<long> Subscriptions = Meter.CreateUpDownCounter<long>(
        "hostloom.websocket.subscriptions",
        "{subscription}",
        "Active gateway subscriptions, tagged by public topic."
    );

    private static readonly Counter<long> EventsSent = Meter.CreateCounter<long>(
        "hostloom.websocket.events.sent",
        "{event}",
        "Event frames successfully written to a WebSocket."
    );

    private static readonly Counter<long> EventsDropped = Meter.CreateCounter<long>(
        "hostloom.websocket.events.dropped",
        "{event}",
        "Event frames not delivered, tagged by public topic and bounded reason."
    );

    private static readonly Histogram<long> QueueBytes = Meter.CreateHistogram<long>(
        "hostloom.websocket.queue.bytes",
        "By",
        "Encoded event-frame bytes accepted into the connection outbound budget."
    );

    private static readonly Histogram<double> SessionDuration = Meter.CreateHistogram<double>(
        "hostloom.websocket.session.duration",
        "s",
        "Session lifetime, tagged by a normalized close reason."
    );

    private static readonly Counter<long> Faults = Meter.CreateCounter<long>(
        "hostloom.websocket.faults",
        "{fault}",
        "Fault frames generated by the gateway, tagged by public fault code."
    );

    private static readonly Counter<long> HandshakeRejected = Meter.CreateCounter<long>(
        "hostloom.websocket.handshake.rejected",
        "{rejection}",
        "Upgrade requests rejected by the gateway handler, tagged by bounded reason."
    );

    internal static void SessionOpened(string protocol) =>
        Sessions.Add(1, new KeyValuePair<string, object?>(ProtocolTag, protocol));

    internal static void SessionClosed(string protocol, double durationSeconds, string reason)
    {
        var protocolTag = new KeyValuePair<string, object?>(ProtocolTag, protocol);
        Sessions.Add(-1, protocolTag);
        SessionDuration.Record(
            durationSeconds,
            new KeyValuePair<string, object?>(CloseReasonTag, reason)
        );
    }

    internal static void SubscriptionAdded(string topic) =>
        Subscriptions.Add(1, new KeyValuePair<string, object?>(TopicTag, topic));

    internal static void SubscriptionRemoved(string topic) =>
        Subscriptions.Add(-1, new KeyValuePair<string, object?>(TopicTag, topic));

    internal static void EventSent(string topic) =>
        EventsSent.Add(1, new KeyValuePair<string, object?>(TopicTag, topic));

    internal static void EventDropped(string topic, string reason) =>
        EventsDropped.Add(
            1,
            new KeyValuePair<string, object?>(TopicTag, topic),
            new KeyValuePair<string, object?>(ReasonTag, reason)
        );

    internal static void EventQueued(string topic, int bytes) =>
        QueueBytes.Record(bytes, new KeyValuePair<string, object?>(TopicTag, topic));

    internal static void FaultGenerated(string code) =>
        Faults.Add(1, new KeyValuePair<string, object?>(FaultCodeTag, code));

    internal static void HandshakeWasRejected(string reason) =>
        HandshakeRejected.Add(1, new KeyValuePair<string, object?>(ReasonTag, reason));

    internal static Activity? StartRequestActivity(string operation, string? protocol)
    {
        var activity = Activities.StartActivity(RequestActivityName, ActivityKind.Server);
        activity?.SetTag(OperationTag, operation);
        if (protocol is not null)
        {
            activity?.SetTag(ProtocolTag, protocol);
        }

        return activity;
    }
}
